site_name: Leafcloud Documentation
nav:
  - Home: index.md
  - Getting Started:
      - Changing your Password: Getting-Started/Changing-your-password.md
      - Enable 2fa: Getting-Started/enabling-2fa-for-openstack.md
      - Launching an Instance: Getting-Started/Launching-an-instance.md
      - Connecting to your instance: Getting-Started/Log-in-to-your-instance.md
      - Configuring Security groups: Getting-Started/Configuring-security-groups.md
      - Key Pairs: Getting-Started/Key-pairs.md
      - Using the Openstack CLI: Getting-Started/Using-Openstack-CLI.md
      - Create a subdomain: Getting-Started/Creating-subdomain.md
  - Volumes:
      - Creating a Volume: volumes/Creating-a-new-volume.md
      - Attaching a Volume: volumes/Attaching-a-volume-to-your-instance.md
      - Creating a Volume Backup: volumes/Creating-a-volume-backup.md
      - Live Volume extension: volumes/Live-volume-extension.md
      - Resizing (extending) a Volume: volumes/Resizing-a-volume.md
      - Making a Volume Snapshot: volumes/Make-a-volume-snapshot.md
  - Object Storage:
      - Using Object Storage (S3): object-storage/using-object-storage.md
  - Network:
      - Creating a Network: network/Creating-a-new-network.md
      - Creating a Router: network/Creating-a-new-router.md
      - Floating IP: network/Floating-IP.md
      - Creating a Load Balancer: network/Creating-a-load-balancer.md
      - Creating a Load Balancer with offload SSL-Certificate: network/Creating-a-load-balancer-with-offload-SSL-Certificate.md
      - Creating a site to site VPN: network/Setup-site-to-site-vpn.md
      - Add an interface to an instance: network/Add-an-interface-to-an-existing-instance.md
  - Orchestration:
      - Terraform:
          - Creating instances: terraform/creating-instances.md
          - Hosting Backend State in Object Store: terraform/tf-state.md
      - Ansible:
          - Creating instances: ansible/creating-instances.md
  - Managed Kubernetes:
      - Creating a Kubernetes Cluster: gardener/creating-a-kubernetes-cluster.md
      - Installing and using gardenctl: gardener/gardenctl.md
      - Temporary kubeconfig: gardener/temporary-kubeconfig.md
      - Advanced network options: gardener/advanced-networking.md
      - WebAssembly in kubernetes: gardener/serverless-webassembly.md
  - Billing and cost:
      - Managing your cloud costs: billing-and-cost/managing-cost.md
  - Kubernetes:
      - Creating a Kubernetes Cluster: kubernetes/creating-a-kubernetes-cluster.md
      - Installing Helm: kubernetes/installing-helm.md
      - Adding NGINX Ingress With Letsencrypt: kubernetes/ingress-with-nginx-letsencrypt.md
      - Creating a PostgreSQL Cluster: kubernetes/creating-a-postgresql-cluster.md
      - Scheduling backups of a PostgreSQL database: kubernetes/scheduling-backups-of-a-PostgreSQL-database.md
      - Implementing Logrotate: kubernetes/implementing-logrotate.md
      - Creating and resizing node groups: kubernetes/creating-and-resizing-node-groups.md
      - Creating a FerretDB database: kubernetes/creating-a-ferretdb-database.md
  - Talos:
      - Create Talos Kubernetes Cluster: talos/creating-talos-cluster.md
  - Claris Filemaker:
      - Deploying Claris Filemaker on Ubuntu: Claris Filemaker/deploying-claris-filemaker-on-ubuntu.md
  - Nextcloud:
      - Deploying Nextcloud: Nextcloud/deploying-nextcloud.md
  - Large Language Models (LLMs):
      - setup private llm on k8s: private-llm/setup-private-llm.md
  - Data Science:
      - All-in-one Jupyter image: data-science/using-the-jupyter-image.md
      - Setting up TensorFlow GPU: data-science/using-a-gpu.md
      - Setting up Jupyter: data-science/running-jupyter.md
      - Setting up Jupyterlab with Miniconda: data-science/running-jupyterlab-with-miniconda.md
theme:
  name: material
  logo: assets/image/leaflogo-no-label.png
  favicon: assets/image/favi.png
extra:
  generator: false
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
