site_name: Leafcloud Tutorials
nav:
    - Home: index.md
    - Quickstart:
          - Changing your Password: Getting-Started/Changing-your-password.md
          - Launching an Instance: Getting-Started/Launching-an-instance.md
          - Connecting to your instance: Getting-Started/Log-in-to-your-instance.md
          - Configuring Security groups: Getting-Started/Configuring-security-groups.md
          - Key Pairs: Getting-Started/Key-pairs.md
          - Using the Openstack CLI: Getting-Started/Using-Openstack-CLI.md
    - Volumes:
          - Creating a Volume: volumes/Creating-a-new-volume.md
          - Attaching a Volumne: volumes/Attaching-a-volume-to-your-instance.md
          - Extending a Volume: volumes/Extending-a-bootable-volume.md
          - Making a Volume Snapshot: volumes/Make-a-volume-snapshot.md
    - Network:
        - Creating a Network: network/Creating-a-new-network.md
        - Creating a Router: network/Creating-a-new-router.md
        - Floating IP: network/Floating-IP.md
        - Creating a Load Balancer: network/Creating-a-load-balancer.md

theme: readthedocs
